/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package M_Recepcionista;

import Comportamientos.IngresoDoctor;
import clases.Doctor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class Crud_Doctor extends javax.swing.JFrame {

    ArrayList<Doctor> arrayDoctor = new ArrayList<Doctor>();
    DefaultTableModel model;
    String group = "";
    IngresoDoctor ingresoDoc = new IngresoDoctor();

    public Crud_Doctor() {
        initComponents();
        cargarTabla();
    }

    public void cedulav() {
        if (ingresoDoc.valida_cedula(TxtCedulaDoc.getText()) == true) {
            RegistrarDoctor();
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar.");
        }
    }

    public void cargarTabla() {
        DefaultTableModel tblModelo = (DefaultTableModel) TablaDoctores.getModel();

        tblModelo.setNumRows(0);
        List<Doctor> listapacientes = ingresoDoc.Lisdoctor();

        listapacientes.stream().forEach(p -> {
            String[] persona = {p.getCedula(), p.getApellido(), p.getNombre(), p.getFecha_nacimiento(), p.getGenero(), p.getTipo_sangre(), p.getTelefono(), p.getDireccion(), p.getId_doctor(), p.getArea(), p.getTitulo()};
            tblModelo.addRow(persona);
        });
    }

    public void RegistrarDoctor() {

        IngresoDoctor doc = new IngresoDoctor();
        doc.setCedula(TxtCedulaDoc.getText());
        doc.setApellido(TxtApellidoDoc.getText());
        doc.setNombre(TxtNombreDoc.getText());
        doc.setFecha_nacimiento(((JTextField) DateDoctorFecha.getDateEditor().getUiComponent()).getText());
        doc.setTelefono(TxtTelefonoDoc.getText());
        doc.setDireccion(TxtDireccionDoc.getText());
        doc.setTipo_sangre(ComboTipoSangreDoc.getSelectedItem().toString());
        doc.setArea(ComboArea.getSelectedItem().toString());
        doc.setGenero(group);
        doc.setTitulo(ComboTitulo.getSelectedItem().toString());
        if (doc.InsertarDoctores()) {
            System.out.println("Conexion Exitosa");
        } else {
            System.out.println("Conexion Erronea");
        }
    }

    public void genero_doctor() {
        Group.add(RadioBtnMasculino);
        Group.add(RadioBtnFemenino);
        Group.add(RadioBtnNoDefinido);
        if (RadioBtnMasculino.isSelected()) {
            group = "Masculino";
        }
        if (RadioBtnFemenino.isSelected()) {
            group = "Femenino";
        }
        if (RadioBtnNoDefinido.isSelected()) {
            group = "No definido";
        }
    }

    public void EliminarDoctor() {
        String cedula = TxtCedulaDoc.getText();
        if (TxtCedulaDoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor debe seleccionar un articulo de la lista");
        } else {
            if (ingresoDoc.eliminarDoctor(cedula)) {
                JOptionPane.showMessageDialog(null, "Registro eliminado con exito...");
                cargarTabla();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TxtNombreDoc = new javax.swing.JTextField();
        TxtTelefonoDoc = new javax.swing.JTextField();
        TxtDireccionDoc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtApellidoDoc = new javax.swing.JTextField();
        TxtCedulaDoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ComboTipoSangreDoc = new javax.swing.JComboBox<>();
        RadioBtnMasculino = new javax.swing.JRadioButton();
        RadioBtnFemenino = new javax.swing.JRadioButton();
        RadioBtnNoDefinido = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ComboArea = new javax.swing.JComboBox<>();
        DateDoctorFecha = new com.toedter.calendar.JDateChooser();
        ComboTitulo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDoctores = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        TxtBuscarcedula = new javax.swing.JTextField();
        BtnGuardarDoc = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnVRegistros = new javax.swing.JButton();
        BtnBuscarDoc = new javax.swing.JButton();
        BtnEliminarDoc = new javax.swing.JButton();
        BtnModificarDoc = new javax.swing.JButton();
        BtnSalirCrudDoc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Doctor"));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        TxtNombreDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreDocKeyTyped(evt);
            }
        });

        TxtTelefonoDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoDocKeyTyped(evt);
            }
        });

        TxtDireccionDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionDocKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cedula: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Apellido: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre: ");

        jLabel5.setText("Fecha de nacimiento: ");

        jLabel6.setText("Telefono: ");

        jLabel7.setText("Direccion: ");

        TxtApellidoDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoDocKeyTyped(evt);
            }
        });

        TxtCedulaDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaDocActionPerformed(evt);
            }
        });
        TxtCedulaDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaDocKeyTyped(evt);
            }
        });

        jLabel8.setText("Tipo de sangre: ");

        ComboTipoSangreDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-" }));
        ComboTipoSangreDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoSangreDocActionPerformed(evt);
            }
        });

        Group.add(RadioBtnMasculino);
        RadioBtnMasculino.setText("Masculino");

        Group.add(RadioBtnFemenino);
        RadioBtnFemenino.setText("Femenino");

        Group.add(RadioBtnNoDefinido);
        RadioBtnNoDefinido.setText("No definido");
        RadioBtnNoDefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnNoDefinidoActionPerformed(evt);
            }
        });

        jLabel10.setText("Genero: ");

        jLabel14.setText("Area:");

        jLabel15.setText("Titulo:");

        ComboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Medicina General" }));

        ComboTitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Medicina Familiar", "Pediatria", "Dermatologia" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(78, 78, 78)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCedulaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtApellidoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtDireccionDoc)
                                .addComponent(TxtTelefonoDoc)
                                .addComponent(DateDoctorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboTipoSangreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RadioBtnMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(RadioBtnFemenino)
                        .addGap(18, 18, 18)
                        .addComponent(RadioBtnNoDefinido))
                    .addComponent(ComboTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TxtCedulaDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(ComboTipoSangreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtApellidoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(RadioBtnMasculino)
                    .addComponent(RadioBtnFemenino)
                    .addComponent(RadioBtnNoDefinido))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel14)
                        .addComponent(ComboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DateDoctorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTelefonoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(ComboTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDireccionDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        TablaDoctores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Apellido", "Nombre", "Fecha de nacimiento", "Genero", "Tipo de sangre", "Telefono", "Direccion", "Id_doctor", "Area", "Titulo"
            }
        ));
        TablaDoctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDoctoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDoctores);

        jLabel11.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel11.setText("Buscar:");

        TxtBuscarcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarcedulaActionPerformed(evt);
            }
        });
        TxtBuscarcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarcedulaKeyTyped(evt);
            }
        });

        BtnGuardarDoc.setText("Guardar");
        BtnGuardarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarDocActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnVRegistros.setText("Ver registros");
        BtnVRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVRegistrosActionPerformed(evt);
            }
        });

        BtnBuscarDoc.setText("Buscar");
        BtnBuscarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarDocActionPerformed(evt);
            }
        });

        BtnEliminarDoc.setText("Eliminar");
        BtnEliminarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarDocActionPerformed(evt);
            }
        });

        BtnModificarDoc.setText("Modificar");
        BtnModificarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarDocActionPerformed(evt);
            }
        });

        BtnSalirCrudDoc.setText("Salir");
        BtnSalirCrudDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirCrudDocActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel3.setText("Crud Doctor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(508, 508, 508)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(798, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(TxtBuscarcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnGuardarDoc)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminarDoc)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimpiar))
                    .addComponent(BtnVRegistros))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BtnBuscarDoc))
                            .addComponent(BtnModificarDoc))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(BtnSalirCrudDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TxtBuscarcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnGuardarDoc)
                            .addComponent(BtnEliminarDoc)
                            .addComponent(BtnLimpiar))
                        .addGap(26, 26, 26)
                        .addComponent(BtnVRegistros))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtnBuscarDoc)
                        .addGap(17, 17, 17)
                        .addComponent(BtnModificarDoc)
                        .addGap(33, 33, 33)
                        .addComponent(BtnSalirCrudDoc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboTipoSangreDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoSangreDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoSangreDocActionPerformed

    private void RadioBtnNoDefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnNoDefinidoActionPerformed

    }//GEN-LAST:event_RadioBtnNoDefinidoActionPerformed

    private void TablaDoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDoctoresMouseClicked
        int i = TablaDoctores.getSelectedRow();

        if (i >= 0) {
            String cedula = TablaDoctores.getValueAt(i, 0).toString();
            String apellido = TablaDoctores.getValueAt(i, 1).toString();
            String nombre = TablaDoctores.getValueAt(i, 2).toString();
            // String fecha_nacimiento = TablaDoctores.getValueAt(i, 3).toString();
            String genero = TablaDoctores.getValueAt(i, 4).toString();
            String tipo_sangre = TablaDoctores.getValueAt(i, 5).toString();
            String telefono = TablaDoctores.getValueAt(i, 6).toString();
            String direccion = TablaDoctores.getValueAt(i, 7).toString();
            String id_doctor = TablaDoctores.getValueAt(i, 8).toString();
            String area = TablaDoctores.getValueAt(i, 9).toString();
            String titulo = TablaDoctores.getValueAt(i, 10).toString();

            TxtCedulaDoc.setText(cedula);
            TxtApellidoDoc.setText(apellido);
            TxtNombreDoc.setText(nombre);
            TxtTelefonoDoc.setText(telefono);
            TxtDireccionDoc.setText(direccion);
            String fecha = (String) TablaDoctores.getValueAt(i, 3);
            Date fechas;
            try {
                fechas = new SimpleDateFormat("dd/MM/yyyy").parse(fecha);
                DateDoctorFecha.setDate(fechas);
            } catch (ParseException ex) {
                Logger.getLogger(Crud_Doctor.class.getName()).log(Level.SEVERE, null, ex);
            }
            ComboTipoSangreDoc.setSelectedItem(tipo_sangre);
            ComboArea.setSelectedItem(area);
            ComboTitulo.setSelectedItem(titulo);
            if (genero.equals("Masculino")) {
                RadioBtnMasculino.setSelected(true);
            }
            if (genero.equals("Femenino")) {
                RadioBtnFemenino.setSelected(true);
            }
            if (genero.equals("No definido")) {
                RadioBtnNoDefinido.setSelected(true);
            }
        } else {

        }
    }//GEN-LAST:event_TablaDoctoresMouseClicked

    private void TxtBuscarcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarcedulaActionPerformed

    }//GEN-LAST:event_TxtBuscarcedulaActionPerformed

    private void BtnGuardarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarDocActionPerformed

        Date naci_doc = DateDoctorFecha.getDate();
        if (!(TxtCedulaDoc.getText().matches("^\\d{10}$"))) {
            JOptionPane.showMessageDialog(null, "Ingresa la cedula.");
        } else {
            if (!(TxtApellidoDoc.getText().matches("^[A-Z].{3,25}$"))) {
                // !()
                JOptionPane.showMessageDialog(null, "Ingresa el apellido.");
            } else {
                if (!(TxtNombreDoc.getText().matches("^[A-Z].{3,25}$"))) {
                    JOptionPane.showMessageDialog(null, "Ingresa el nombre.");
                } else {
                    if (naci_doc == null) {
                        JOptionPane.showMessageDialog(null, "Verifique el ingreso de la fecha de nacimiento.");
                    } else {
                        if (!(TxtTelefonoDoc.getText().matches("^\\d{8}$"))) {
                            JOptionPane.showMessageDialog(null, "Ingresa el telefono.");
                        } else {
                            if (TxtDireccionDoc.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Ingresa la direccion.");
                            } else {
                                if (ComboTipoSangreDoc.getSelectedItem().toString().equals("Seleccione")) {
                                    JOptionPane.showMessageDialog(null, "Escoje tipo de sangre.");
                                } else {
                                    if (Group.isSelected(null)) {
                                        JOptionPane.showMessageDialog(null, "Escoje genero");
                                    } else {
                                        if (ComboArea.getSelectedItem().toString().equals("Seleccione")) {
                                            JOptionPane.showMessageDialog(null, "Escoje el area");
                                        } else {
                                            if (ComboTitulo.getSelectedItem().toString().equals("Seleccione")) {
                                                JOptionPane.showMessageDialog(null, "Escoje el titulo");
                                            } else {
                                                if (ingresoDoc.valida_cedula(TxtCedulaDoc.getText()) == true) {
                                                    genero_doctor();
                                                    RegistrarDoctor();
                                                    cargarTabla();
                                                    limpiar_datosDoctor();
                                                } else {
                                                    JOptionPane.showMessageDialog(null, "Error la cedula ya existe en los registros.");
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BtnGuardarDocActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed

        limpiar_datosDoctor();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    public void limpiar_datosDoctor() {
        TxtCedulaDoc.setText("");
        TxtApellidoDoc.setText("");
        TxtNombreDoc.setText("");
        TxtTelefonoDoc.setText("");
        TxtDireccionDoc.setText("");
        ComboArea.setSelectedItem("Seleccione");
        ComboTipoSangreDoc.setSelectedItem("Seleccione");
        ComboTitulo.setSelectedItem("Seleccione");
        ((JTextField) DateDoctorFecha.getDateEditor().getUiComponent()).setText(null);
        Group.clearSelection();

    }
    private void BtnVRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVRegistrosActionPerformed

        cargarTabla();
    }//GEN-LAST:event_BtnVRegistrosActionPerformed

    public void Busqueda_doctor() {
        DefaultTableModel tblModelo = (DefaultTableModel) TablaDoctores.getModel();

        tblModelo.setNumRows(0);
        List<Doctor> listapacientes = ingresoDoc.consulta_Doctor(TxtBuscarcedula.getText());

        listapacientes.stream().forEach(p -> {
            String[] persona = {p.getCedula(), p.getApellido(), p.getNombre(), p.getFecha_nacimiento(), p.getGenero(), p.getTipo_sangre(), p.getTelefono(), p.getDireccion(), p.getId_doctor(), p.getArea(), p.getTitulo()};
            tblModelo.addRow(persona);
        });
    }
    private void BtnBuscarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarDocActionPerformed

        if (!(TxtBuscarcedula.getText().equals(""))) {
            Busqueda_doctor();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe ingresar la cedula en el campo, para realizar la consulta.", "Precaución  ", JOptionPane.WARNING_MESSAGE);
        }
        TxtBuscarcedula.setText("");
    }//GEN-LAST:event_BtnBuscarDocActionPerformed

    private void BtnEliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarDocActionPerformed

        int i = TablaDoctores.getSelectedRow();
        if (i >= 0) {

            int t = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este registro?", "Verificación de eliminar.", JOptionPane.YES_NO_OPTION);
            if (t == JOptionPane.YES_OPTION) {
                EliminarDoctor();
                cargarTabla();
                limpiar_datosDoctor();
            }
            if (t == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada.");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el registro para eliminar.");
        }
    }//GEN-LAST:event_BtnEliminarDocActionPerformed

    public void modificarDatosPac() {

        IngresoDoctor indoc = new IngresoDoctor();

        indoc.setCedula(TxtCedulaDoc.getText());
        indoc.setApellido(TxtApellidoDoc.getText());
        indoc.setNombre(TxtNombreDoc.getText());
        indoc.setFecha_nacimiento(((JTextField) DateDoctorFecha.getDateEditor().getUiComponent()).getText());
        indoc.setGenero(group);
        indoc.setTipo_sangre(ComboTipoSangreDoc.getSelectedItem().toString());
        indoc.setTelefono(TxtTelefonoDoc.getText());
        indoc.setDireccion(TxtDireccionDoc.getText());
        indoc.setArea(ComboArea.getSelectedItem().toString());
        indoc.setTitulo(ComboTitulo.getSelectedItem().toString());
        if (indoc.ModificarDoctor(TxtCedulaDoc.getText())) {
            System.out.println("Si se ingreso a tu corazon");
            JOptionPane.showMessageDialog(null, "Los datos se modificaron correctamente. ");
        } else {
            System.out.println("esta roto tu corazon");
        }

    }
    private void BtnModificarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarDocActionPerformed

        int i = TablaDoctores.getSelectedRow();
        if (i >= 0) {
            Date naci_doc = DateDoctorFecha.getDate();
            if (!(TxtCedulaDoc.getText().matches("^\\d{10}$"))) {
                JOptionPane.showMessageDialog(null, "Ingresa la cedula.");
            } else {
                if (!(TxtApellidoDoc.getText().matches("^[A-Z].{3,25}$"))) {
                    // !()
                    JOptionPane.showMessageDialog(null, "Ingresa el apellido.");
                } else {
                    if (!(TxtNombreDoc.getText().matches("^[A-Z].{3,25}$"))) {
                        JOptionPane.showMessageDialog(null, "Ingresa el nombre.");
                    } else {
                        if (naci_doc == null) {
                            JOptionPane.showMessageDialog(null, "Verifique el ingreso de la fecha de nacimiento.");
                        } else {
                            if (!(TxtTelefonoDoc.getText().matches("^\\d{8}$"))) {
                                JOptionPane.showMessageDialog(null, "Ingresa el telefono.");
                            } else {
                                if (TxtDireccionDoc.getText().isEmpty()) {
                                    JOptionPane.showMessageDialog(null, "Ingresa la direccion.");
                                } else {
                                    if (ComboTipoSangreDoc.getSelectedItem().toString().equals("Seleccione")) {
                                        JOptionPane.showMessageDialog(null, "Escoje tipo de sangre.");
                                    } else {
                                        if (Group.isSelected(null)) {
                                            JOptionPane.showMessageDialog(null, "Escoje genero");
                                        } else {
                                            if (ComboArea.getSelectedItem().toString().equals("Seleccione")) {
                                                JOptionPane.showMessageDialog(null, "Escoje el area");
                                            } else {
                                                if (ComboTitulo.getSelectedItem().toString().equals("Seleccione")) {
                                                    JOptionPane.showMessageDialog(null, "Escoje el titulo");
                                                } else {
                                                    genero_doctor();
                                                    modificarDatosPac();
                                                    cargarTabla();
                                                    limpiar_datosDoctor();
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el registro para modificar.");
        }
    }//GEN-LAST:event_BtnModificarDocActionPerformed

    private void BtnSalirCrudDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirCrudDocActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas salir del crud de paciente.", "Confirma", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
//            sdf ni = new sdf();
//            ni.setVisible(true);
//            dispose();
            Menu_Recepcionista mrep = new Menu_Recepcionista();
            mrep.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Sesión cancelada.");
        }
    }//GEN-LAST:event_BtnSalirCrudDocActionPerformed

    private void TxtCedulaDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaDocKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros por favor.");
        }
    }//GEN-LAST:event_TxtCedulaDocKeyTyped

    private void TxtApellidoDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoDocKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo letras");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtApellidoDocKeyTyped

    private void TxtCedulaDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaDocActionPerformed

    private void TxtNombreDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreDocKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo letras");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtNombreDocKeyTyped

    private void TxtDireccionDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionDocKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo letras");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtDireccionDocKeyTyped

    private void TxtTelefonoDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoDocKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros por favor.");
        }
    }//GEN-LAST:event_TxtTelefonoDocKeyTyped

    private void TxtBuscarcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarcedulaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros por favor.");
        }
    }//GEN-LAST:event_TxtBuscarcedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarDoc;
    private javax.swing.JButton BtnEliminarDoc;
    private javax.swing.JButton BtnGuardarDoc;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificarDoc;
    private javax.swing.JButton BtnSalirCrudDoc;
    private javax.swing.JButton BtnVRegistros;
    private javax.swing.JComboBox<String> ComboArea;
    private javax.swing.JComboBox<String> ComboTipoSangreDoc;
    private javax.swing.JComboBox<String> ComboTitulo;
    private com.toedter.calendar.JDateChooser DateDoctorFecha;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JRadioButton RadioBtnFemenino;
    private javax.swing.JRadioButton RadioBtnMasculino;
    private javax.swing.JRadioButton RadioBtnNoDefinido;
    private javax.swing.JTable TablaDoctores;
    private javax.swing.JTextField TxtApellidoDoc;
    private javax.swing.JTextField TxtBuscarcedula;
    private javax.swing.JTextField TxtCedulaDoc;
    private javax.swing.JTextField TxtDireccionDoc;
    private javax.swing.JTextField TxtNombreDoc;
    private javax.swing.JTextField TxtTelefonoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
