/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package M_Recepcionista;

import Comportamientos.IngresoPacientes;
import M_Recepcionista.Menu_Recepcionista;
import clases.Paciente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Crud_Paciente extends javax.swing.JFrame {

    public static ArrayList<Paciente> Lista_Pacientes = new ArrayList<Paciente>();
    String edadpac = "", discapacidadPac = "", generopac = "";
    Paciente pacient = new Paciente();
    IngresoPacientes ingresopa = new IngresoPacientes();

    public Crud_Paciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        //verRegistrosPaciente();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoGeneroPac = new javax.swing.ButtonGroup();
        GrupoDiscapacidadPac = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TxtNombrePac = new javax.swing.JTextField();
        TxtTelefonoPac = new javax.swing.JTextField();
        TxtDireccionPac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtApellidoPac = new javax.swing.JTextField();
        TxtCedulaPac = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ComboTipoSangrePac = new javax.swing.JComboBox<>();
        RadioBtnMasculino = new javax.swing.JRadioButton();
        RadioBtnFemenino = new javax.swing.JRadioButton();
        RadioBtnNoDefinido = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RadioDiscapaNO = new javax.swing.JRadioButton();
        RadioDiscapaSI = new javax.swing.JRadioButton();
        DateFnaciPaci = new com.toedter.calendar.JDateChooser();
        ComboTipoAlergiasPac = new javax.swing.JComboBox<>();
        BtnGuardarDoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPaciente = new javax.swing.JTable();
        BtnListaPaciente = new javax.swing.JButton();
        BtnEliminarPac = new javax.swing.JButton();
        BtnModificarPac = new javax.swing.JButton();
        TxtBuscarPac = new javax.swing.JTextField();
        BtnBuscarPac = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BtnSalirCrudDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));

        TxtNombrePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombrePacActionPerformed(evt);
            }
        });
        TxtNombrePac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombrePacKeyTyped(evt);
            }
        });

        TxtTelefonoPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoPacActionPerformed(evt);
            }
        });
        TxtTelefonoPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoPacKeyTyped(evt);
            }
        });

        TxtDireccionPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionPacKeyTyped(evt);
            }
        });

        jLabel1.setText("Cedula: ");

        jLabel2.setText("Apellido: ");

        jLabel4.setText("Nombre: ");

        jLabel5.setText("Fecha de nacimiento: ");

        jLabel6.setText("Telefono: ");

        jLabel7.setText("Direccion: ");

        TxtApellidoPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoPacKeyTyped(evt);
            }
        });

        TxtCedulaPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCedulaPacKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaPacKeyTyped(evt);
            }
        });

        jLabel8.setText("Tipo de sangre: ");

        ComboTipoSangrePac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-", " " }));
        ComboTipoSangrePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoSangrePacActionPerformed(evt);
            }
        });

        GrupoGeneroPac.add(RadioBtnMasculino);
        RadioBtnMasculino.setText("Masculino");

        GrupoGeneroPac.add(RadioBtnFemenino);
        RadioBtnFemenino.setText("Femenino");

        GrupoGeneroPac.add(RadioBtnNoDefinido);
        RadioBtnNoDefinido.setText("No definido");

        jLabel10.setText("Genero: ");

        jLabel12.setText("Alergia: ");

        jLabel13.setText("Discapacidad: ");

        GrupoDiscapacidadPac.add(RadioDiscapaNO);
        RadioDiscapaNO.setText("NO");

        GrupoDiscapacidadPac.add(RadioDiscapaSI);
        RadioDiscapaSI.setText("SI");

        ComboTipoAlergiasPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Estacional", "Interior", "Mascotas", "Cutáneas", "Alimentarias", "Polen", "Sol" }));
        ComboTipoAlergiasPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoAlergiasPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtTelefonoPac, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(DateFnaciPaci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(RadioDiscapaSI)
                                .addGap(18, 18, 18)
                                .addComponent(RadioDiscapaNO))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(RadioBtnMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtnFemenino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtnNoDefinido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtDireccionPac, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboTipoAlergiasPac, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TxtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(TxtDireccionPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(ComboTipoAlergiasPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(ComboTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(DateFnaciPaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(RadioBtnMasculino)
                        .addComponent(RadioBtnFemenino)
                        .addComponent(RadioBtnNoDefinido)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTelefonoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(RadioDiscapaSI)
                    .addComponent(RadioDiscapaNO))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        BtnGuardarDoc.setText("Guardar");
        BtnGuardarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarDocActionPerformed(evt);
            }
        });

        TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Apellido", "Nombre", "Fecha de nacimiento", "Genero", "Tipo de sangre", "telefono", "direccion", "Id_paciente", "Alergias", "Discapacidad"
            }
        ));
        TablaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPaciente);

        BtnListaPaciente.setText("Ver Registros");
        BtnListaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaPacienteActionPerformed(evt);
            }
        });

        BtnEliminarPac.setText("Eliminar");
        BtnEliminarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarPacActionPerformed(evt);
            }
        });

        BtnModificarPac.setText("Modificar");
        BtnModificarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarPacActionPerformed(evt);
            }
        });

        TxtBuscarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarPacActionPerformed(evt);
            }
        });
        TxtBuscarPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarPacKeyTyped(evt);
            }
        });

        BtnBuscarPac.setText("Buscar");
        BtnBuscarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPacActionPerformed(evt);
            }
        });

        jLabel16.setText("Buscar Usuario por cedula");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Registro Paciente");

        BtnSalirCrudDoc.setText("Salir");
        BtnSalirCrudDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirCrudDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalirCrudDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BtnSalirCrudDoc)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(BtnGuardarDoc)
                            .addComponent(BtnListaPaciente)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BtnBuscarPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminarPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnModificarPac)))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BtnGuardarDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnListaPaciente))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TxtBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarPac)
                    .addComponent(BtnEliminarPac)
                    .addComponent(BtnModificarPac))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboTipoSangrePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoSangrePacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoSangrePacActionPerformed

    public void cedulav() {
        if (ingresopa.valida_cedula(TxtCedulaPac.getText()) == true) {
            registrarPaciente();
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardarrrrrrrrrr.");
        }
    }

    private void cargarTabla() {
        DefaultTableModel tblModelo = (DefaultTableModel) TablaPaciente.getModel();

        tblModelo.setNumRows(0);
        List<Paciente> listapacientes = ingresopa.pacientes();

        listapacientes.stream().forEach(p -> {
            String[] persona = {p.getCedula(), p.getApellido(), p.getNombre(), p.getFecha_nacimiento(), p.getGenero(), p.getTipo_sangre(), p.getTelefono(), p.getDireccion(), p.getId_paciente(), p.getAlergias(), p.getDiscapacidad()};
            tblModelo.addRow(persona);
        });
        // limpiarCampos();
    }

    private void Busqueda_paciente() {
        DefaultTableModel tblModelo = (DefaultTableModel) TablaPaciente.getModel();

        tblModelo.setNumRows(0);
        List<Paciente> listapacientes = ingresopa.consulta_paciente(TxtCedulaPac.getText());

        listapacientes.stream().forEach(p -> {
            String[] persona = {p.getCedula(), p.getApellido(), p.getNombre(), p.getFecha_nacimiento(), p.getGenero(), p.getTipo_sangre(), p.getTelefono(), p.getDireccion(), p.getId_paciente(), p.getAlergias(), p.getDiscapacidad()};
            tblModelo.addRow(persona);
        });
        // limpiarCampos();
    }

    public void registrarPaciente() {
        IngresoPacientes inpac = new IngresoPacientes();
        inpac.setCedula(TxtCedulaPac.getText());
        inpac.setApellido(TxtApellidoPac.getText());
        inpac.setNombre(TxtNombrePac.getText());
        inpac.setFecha_nacimiento(((JTextField) DateFnaciPaci.getDateEditor().getUiComponent()).getText());
        inpac.setGenero(generopac);
        inpac.setTipo_sangre(ComboTipoSangrePac.getSelectedItem().toString());
        inpac.setTelefono(TxtTelefonoPac.getText());
        inpac.setDireccion(TxtDireccionPac.getText());
        inpac.setAlergias(ComboTipoAlergiasPac.getSelectedItem().toString());
        inpac.setDiscapacidad(discapacidadPac);
        if (inpac.insertatPacientes()) {
            System.out.println("Si se ingreso a tu corazon");
        } else {
            System.out.println("esta roto tu corazon");
        }
    }
    private void BtnGuardarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarDocActionPerformed

        Date fecha_naci = DateFnaciPaci.getDate();
        if (!(TxtCedulaPac.getText().matches("^\\d{10}$"))) {
            JOptionPane.showMessageDialog(null, "Verifique la cedula.");
        } else {
            if (!(TxtApellidoPac.getText().matches("^[A-Z].{3,25}$"))) {
                // !()
                JOptionPane.showMessageDialog(null, "Verifique el apellido.");
            } else {
                if (!(TxtNombrePac.getText().matches("^[A-Z].{3,25}$"))) {
                    JOptionPane.showMessageDialog(null, "Verifique el nombre.");
                } else {
                    if (fecha_naci == null) {
                        JOptionPane.showMessageDialog(null, "Verifique el ingreso de la fecha de nacimiento.");
                    } else {
                        if (!(TxtTelefonoPac.getText().matches("^\\d{8}$"))) {
                            JOptionPane.showMessageDialog(null, "Verifique el teléfono.");
                        } else {
                            if (TxtDireccionPac.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Verifique la dirección u domicilio.");
                            } else {
                                if (ComboTipoAlergiasPac.getSelectedItem().toString().equals("Seleccione")) {
                                    JOptionPane.showMessageDialog(null, "Seleccione algún tipo de alergia.");
                                } else {
                                    if (ComboTipoSangrePac.getSelectedItem().toString().equals("Seleccione")) {
                                        JOptionPane.showMessageDialog(null, "Seleccione algún tipo de sangre");
                                    } else {
                                        if (GrupoGeneroPac.isSelected(null)) {
                                            JOptionPane.showMessageDialog(null, "Seleccione genero.");
                                        } else {
                                            if (GrupoDiscapacidadPac.isSelected(null)) {
                                                JOptionPane.showMessageDialog(null, "Seleccione la si tiene o no discapacidad.");
                                            } else {
                                                if (ingresopa.valida_cedula(TxtCedulaPac.getText()) == true) {
                                                    genero_paciente();
                                                    discapacidad_paciente();
                                                    registrarPaciente();
                                                    cargarTabla();
                                                    limpiar_datosPaciente();
                                                } else {
                                                    JOptionPane.showMessageDialog(null, "Error la cedula ya existe en los registros.");
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BtnGuardarDocActionPerformed

    private void BtnSalirCrudDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirCrudDocActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas salir del crud de paciente.", "Confirma", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
//            sdf ni = new sdf();
//            ni.setVisible(true);
//            dispose();
            Menu_Recepcionista mrep = new Menu_Recepcionista();
            mrep.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Sesión cancelada.");
        }
    }//GEN-LAST:event_BtnSalirCrudDocActionPerformed

    private void BtnListaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaPacienteActionPerformed
        // TODO add your handling code here:
        // verRegistrosPaciente();
        cargarTabla();
    }//GEN-LAST:event_BtnListaPacienteActionPerformed

    private void ComboTipoAlergiasPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoAlergiasPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoAlergiasPacActionPerformed

    private void BtnEliminarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarPacActionPerformed
        // TODO add your handling code here:
        int i = TablaPaciente.getSelectedRow();
        if (i >= 0) {

            int t = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este registro?", "Verificación de eliminar.", JOptionPane.YES_NO_OPTION);
            if (t == JOptionPane.YES_OPTION) {
                EliminarPaciente();
                limpiar_datosPaciente();
                JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
            }
            if (t == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada.");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el registro para eliminar.");
        }
    }//GEN-LAST:event_BtnEliminarPacActionPerformed

    public void EliminarPaciente() {
        String cedula = TxtCedulaPac.getText();
        if (TxtCedulaPac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor debe seleccionar un articulo de la lista");
        } else {
            if (ingresopa.eliminarPaciente(cedula)) {
                JOptionPane.showMessageDialog(null, "Registro eliminado con exito...");
                cargarTabla();
            }
        }
    }
    private void TablaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPacienteMouseClicked
        int i = TablaPaciente.getSelectedRow();

        if (i >= 0) {
            String cedula = TablaPaciente.getValueAt(i, 0).toString();
            String apellido = TablaPaciente.getValueAt(i, 1).toString();
            String nombre = TablaPaciente.getValueAt(i, 2).toString();
            //  String fecha_nacimiento = TablaPaciente.getValueAt(i, 3).toString();
            String genero = TablaPaciente.getValueAt(i, 4).toString();
            String tipo_sangre = TablaPaciente.getValueAt(i, 5).toString();
            String telefono = TablaPaciente.getValueAt(i, 6).toString();
            String direccion = TablaPaciente.getValueAt(i, 7).toString();
            String id_paciente = TablaPaciente.getValueAt(i, 8).toString();
            String alergias = TablaPaciente.getValueAt(i, 9).toString();
            String discapacidad = TablaPaciente.getValueAt(i, 10).toString();
            TxtCedulaPac.setText(cedula);
            TxtApellidoPac.setText(apellido);
            TxtNombrePac.setText(nombre);
            TxtTelefonoPac.setText(telefono);
            TxtDireccionPac.setText(direccion);
            ComboTipoAlergiasPac.setSelectedItem(alergias);
            String fecha = (String) TablaPaciente.getValueAt(i, 3);
            Date fechas;
            try {
                fechas = new SimpleDateFormat("dd/MM/yyyy").parse(fecha);
                DateFnaciPaci.setDate(fechas);
            } catch (ParseException ex) {
                Logger.getLogger(Crud_Paciente.class.getName()).log(Level.SEVERE, null, ex);
            }

            ComboTipoSangrePac.setSelectedItem(tipo_sangre);
            if (genero.equals("Masculino")) {
                RadioBtnMasculino.setSelected(true);
            }
            if (genero.equals("Femenino")) {
                RadioBtnFemenino.setSelected(true);
            }
            if (genero.equals("No definido")) {
                RadioBtnNoDefinido.setSelected(true);
            }
            //  ComboEstadocivilPac.setSelectedItem(estado_civilp);
            if (discapacidad.equals("SI")) {
                RadioDiscapaSI.setSelected(true);
            }
            if (discapacidad.equals("NO")) {
                RadioDiscapaNO.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "6");
        }
    }//GEN-LAST:event_TablaPacienteMouseClicked

    private void BtnModificarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarPacActionPerformed

        int i = TablaPaciente.getSelectedRow();
        if (i >= 0) {

            genero_paciente();
            discapacidad_paciente();
            modificarDatosPac();
            cargarTabla();
            limpiar_datosPaciente();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el registro para modificar.");
        }
    }//GEN-LAST:event_BtnModificarPacActionPerformed

    public void modificarDatosPac() {

        IngresoPacientes inpaci = new IngresoPacientes();

        inpaci.setCedula(TxtCedulaPac.getText());
        inpaci.setApellido(TxtApellidoPac.getText());
        inpaci.setNombre(TxtNombrePac.getText());
        inpaci.setFecha_nacimiento(((JTextField) DateFnaciPaci.getDateEditor().getUiComponent()).getText());
        inpaci.setGenero(generopac);
        inpaci.setTipo_sangre(ComboTipoSangrePac.getSelectedItem().toString());
        inpaci.setTelefono(TxtTelefonoPac.getText());
        inpaci.setDireccion(TxtDireccionPac.getText());
        inpaci.setAlergias(ComboTipoAlergiasPac.getSelectedItem().toString());
        inpaci.setDiscapacidad(discapacidadPac);

        if (inpaci.ModificarPaciente(TxtCedulaPac.getText())) {
            System.out.println("Si se ingreso a tu corazon");
        } else {
            System.out.println("esta roto tu corazon");
        }

    }
    private void BtnBuscarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPacActionPerformed

        if (!(TxtBuscarPac.getText().equals(""))) {
            Busqueda_paciente();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe ingresar la cedula en el campo, para realizar la consulta.", "Precaución  ", JOptionPane.WARNING_MESSAGE);
        }
        TxtBuscarPac.setText("");
    }//GEN-LAST:event_BtnBuscarPacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar_datosPaciente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtNombrePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombrePacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombrePacActionPerformed

    private void TxtCedulaPacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaPacKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaPacKeyReleased

    private void TxtBuscarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarPacActionPerformed

    private void TxtCedulaPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaPacKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros por favor.");
        }
    }//GEN-LAST:event_TxtCedulaPacKeyTyped

    private void TxtTelefonoPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoPacActionPerformed

    private void TxtTelefonoPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoPacKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros por favor.");
        }
    }//GEN-LAST:event_TxtTelefonoPacKeyTyped

    private void TxtApellidoPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoPacKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo letras");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtApellidoPacKeyTyped

    private void TxtNombrePacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombrePacKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo letras");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtNombrePacKeyTyped

    private void TxtDireccionPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionPacKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo letras");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtDireccionPacKeyTyped

    private void TxtBuscarPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarPacKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros por favor.");
        }
    }//GEN-LAST:event_TxtBuscarPacKeyTyped

    public void limpiar_datosPaciente() {
        TxtCedulaPac.setText("");
        TxtApellidoPac.setText("");
        TxtNombrePac.setText("");
        TxtTelefonoPac.setText("");
        TxtDireccionPac.setText("");
        ComboTipoAlergiasPac.setSelectedItem("Seleccione");
        ComboTipoSangrePac.setSelectedItem("Seleccione");
        ((JTextField) DateFnaciPaci.getDateEditor().getUiComponent()).setText(null);
        GrupoGeneroPac.clearSelection();
        GrupoDiscapacidadPac.clearSelection();

    }

    public void genero_paciente() {
        GrupoGeneroPac.add(RadioBtnMasculino);
        GrupoGeneroPac.add(RadioBtnFemenino);
        GrupoGeneroPac.add(RadioBtnNoDefinido);
        if (RadioBtnMasculino.isSelected()) {
            generopac = "Masculino";
        }
        if (RadioBtnFemenino.isSelected()) {
            generopac = "Femenino";
        }
        if (RadioBtnNoDefinido.isSelected()) {
            generopac = "No definido";
        }
    }

    public void discapacidad_paciente() {
        GrupoDiscapacidadPac.add(RadioDiscapaSI);
        GrupoDiscapacidadPac.add(RadioDiscapaNO);
        if (RadioDiscapaSI.isSelected()) {
            discapacidadPac = "SI";
        }
        if (RadioDiscapaNO.isSelected()) {
            discapacidadPac = "NO";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarPac;
    private javax.swing.JButton BtnEliminarPac;
    private javax.swing.JButton BtnGuardarDoc;
    private javax.swing.JButton BtnListaPaciente;
    private javax.swing.JButton BtnModificarPac;
    private javax.swing.JButton BtnSalirCrudDoc;
    private javax.swing.JComboBox<String> ComboTipoAlergiasPac;
    private javax.swing.JComboBox<String> ComboTipoSangrePac;
    private com.toedter.calendar.JDateChooser DateFnaciPaci;
    private javax.swing.ButtonGroup GrupoDiscapacidadPac;
    private javax.swing.ButtonGroup GrupoGeneroPac;
    private javax.swing.JRadioButton RadioBtnFemenino;
    private javax.swing.JRadioButton RadioBtnMasculino;
    private javax.swing.JRadioButton RadioBtnNoDefinido;
    private javax.swing.JRadioButton RadioDiscapaNO;
    private javax.swing.JRadioButton RadioDiscapaSI;
    private javax.swing.JTable TablaPaciente;
    private javax.swing.JTextField TxtApellidoPac;
    private javax.swing.JTextField TxtBuscarPac;
    private javax.swing.JTextField TxtCedulaPac;
    private javax.swing.JTextField TxtDireccionPac;
    private javax.swing.JTextField TxtNombrePac;
    private javax.swing.JTextField TxtTelefonoPac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
