/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package M_Recepcionista;

import Comportamientos_recepcionista.IngresoPacientes;
import M_Recepcionista.Menu_Recepcionista;
import clases.Paciente;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Crud_Paciente extends javax.swing.JFrame {

    public static ArrayList<Paciente> Lista_Pacientes = new ArrayList<Paciente>();
    String edadpac = "", discapacidadPac = "", generopac = "";
    Paciente pacient = new Paciente();
    IngresoPacientes ingresopa = new IngresoPacientes();

    public Crud_Paciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        verRegistrosPaciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoGeneroPac = new javax.swing.ButtonGroup();
        GrupoDiscapacidadPac = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TxtNombrePac = new javax.swing.JTextField();
        TxtTelefonoPac = new javax.swing.JTextField();
        TxtDireccionPac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtApellidoPac = new javax.swing.JTextField();
        TxtCedulaPac = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ComboTipoSangrePac = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        SpinerEdadPac = new javax.swing.JSpinner();
        RadioBtnMasculino = new javax.swing.JRadioButton();
        RadioBtnFemenino = new javax.swing.JRadioButton();
        RadioBtnNoDefinido = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ComboEstadocivilPac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TxtOcupacionPac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ComboTipoEstudiPac = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        RadioDiscapaNO = new javax.swing.JRadioButton();
        RadioDiscapaSI = new javax.swing.JRadioButton();
        DateFnaciPaci = new com.toedter.calendar.JDateChooser();
        ComboTipoAlergiasPac = new javax.swing.JComboBox<>();
        BtnGuardarDoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPaciente = new javax.swing.JTable();
        BtnListaPaciente = new javax.swing.JButton();
        BtnEliminarPac = new javax.swing.JButton();
        BtnModificarPac = new javax.swing.JButton();
        TxtBuscarPac = new javax.swing.JTextField();
        BtnBuscarPac = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BtnSalirCrudDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));

        jLabel1.setText("Cedula: ");

        jLabel2.setText("Apellido: ");

        jLabel4.setText("Nombre: ");

        jLabel5.setText("Fecha de nacimiento: ");

        jLabel6.setText("Telefono: ");

        jLabel7.setText("Direccion: ");

        jLabel8.setText("Tipo de sangre: ");

        ComboTipoSangrePac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-", " " }));
        ComboTipoSangrePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoSangrePacActionPerformed(evt);
            }
        });

        jLabel9.setText("Edad: ");

        SpinerEdadPac.setModel(new javax.swing.SpinnerNumberModel(30, 30, 70, 1));

        GrupoGeneroPac.add(RadioBtnMasculino);
        RadioBtnMasculino.setText("Masculino");

        GrupoGeneroPac.add(RadioBtnFemenino);
        RadioBtnFemenino.setText("Femenino");

        GrupoGeneroPac.add(RadioBtnNoDefinido);
        RadioBtnNoDefinido.setText("No definido");

        jLabel10.setText("Genero: ");

        jLabel12.setText("Alergia: ");

        jLabel14.setText("Estado civil: ");

        ComboEstadocivilPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Soltero/a", "Casado/a", "Unioon Libre", "Divorciado/a", "Viudo/a" }));

        jLabel3.setText(" Ocupación: ");

        jLabel15.setText("Nivel de Estudio:");

        ComboTipoEstudiPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Sin estudios", "Personas analfabetas", "Primarios", "Profesionales", "Secundarios", "Medio-superiores", "Superiores" }));

        jLabel13.setText("Discapacidad: ");

        GrupoDiscapacidadPac.add(RadioDiscapaNO);
        RadioDiscapaNO.setText("NO");

        GrupoDiscapacidadPac.add(RadioDiscapaSI);
        RadioDiscapaSI.setText("SI");

        ComboTipoAlergiasPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Estacional", "Interior", "Mascotas", "Cutáneas", "Alimentarias", "Polen", "Sol" }));
        ComboTipoAlergiasPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoAlergiasPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtDireccionPac, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(TxtTelefonoPac, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(ComboTipoAlergiasPac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateFnaciPaci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtOcupacionPac, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinerEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioBtnMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(RadioBtnFemenino)
                        .addGap(18, 18, 18)
                        .addComponent(RadioBtnNoDefinido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioDiscapaSI)
                        .addGap(18, 18, 18)
                        .addComponent(RadioDiscapaNO))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboEstadocivilPac, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboTipoEstudiPac, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtOcupacionPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(SpinerEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(ComboTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)
                        .addComponent(RadioBtnMasculino)
                        .addComponent(RadioBtnFemenino)
                        .addComponent(RadioBtnNoDefinido))
                    .addComponent(DateFnaciPaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTelefonoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(ComboEstadocivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDireccionPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(ComboTipoEstudiPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(RadioDiscapaNO)
                    .addComponent(RadioDiscapaSI)
                    .addComponent(ComboTipoAlergiasPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        BtnGuardarDoc.setText("Guardar");
        BtnGuardarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarDocActionPerformed(evt);
            }
        });

        TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Apellido", "Nombre", "Fecha de nacimiento", "Telefono", "Direccion", "Alergia", "Ocupación", "Edad", "Tipo sangre", "Genero", "Estado civil", "Nivel Estudio", "Discapacidad"
            }
        ));
        TablaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPaciente);

        BtnListaPaciente.setText("Ver Registros");
        BtnListaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaPacienteActionPerformed(evt);
            }
        });

        BtnEliminarPac.setText("Eliminar");
        BtnEliminarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarPacActionPerformed(evt);
            }
        });

        BtnModificarPac.setText("Modificar");
        BtnModificarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarPacActionPerformed(evt);
            }
        });

        BtnBuscarPac.setText("Buscar");
        BtnBuscarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPacActionPerformed(evt);
            }
        });

        jLabel16.setText("Buscar Usuario por cedula");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Registro Paciente");

        BtnSalirCrudDoc.setText("Salir");
        BtnSalirCrudDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirCrudDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalirCrudDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BtnSalirCrudDoc)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscarPac)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminarPac)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificarPac))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(BtnGuardarDoc)
                            .addComponent(BtnListaPaciente))))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(BtnGuardarDoc)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(BtnListaPaciente)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscarPac)
                    .addComponent(BtnEliminarPac)
                    .addComponent(BtnModificarPac)
                    .addComponent(jLabel16)
                    .addComponent(TxtBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboTipoSangrePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoSangrePacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoSangrePacActionPerformed

    public void registrarPaciente() {

        String cedulap = TxtCedulaPac.getText();
        String apellidop = TxtApellidoPac.getText();
        String nombrep = TxtNombrePac.getText();
        SimpleDateFormat formatoFechap = new SimpleDateFormat("yyyy-MM-dd");
        String fecha_nacidopa = formatoFechap.format(DateFnaciPaci.getDate());
        String telefonop = TxtTelefonoPac.getText();
        String direccionp = TxtDireccionPac.getText();
        String alergiap = ComboTipoAlergiasPac.getSelectedItem().toString();
        String ocupacionp = TxtOcupacionPac.getText();
        int edadp = Integer.parseInt(edadpac);
        String tiposangrep = ComboTipoSangrePac.getSelectedItem().toString();
        String generop = generopac;
        String estado_civilp = ComboEstadocivilPac.getSelectedItem().toString();
        String nivel_estudio = ComboTipoEstudiPac.getSelectedItem().toString();
        String discapacidadp = discapacidadPac;
        if (cedulap.isEmpty() || apellidop.isEmpty() || nombrep.isEmpty() || fecha_nacidopa.isEmpty() || telefonop.isEmpty() || direccionp.isEmpty() || alergiap.isEmpty() || ocupacionp.isEmpty() || edadp <= 0 || tiposangrep.isEmpty() || generop.isEmpty() || estado_civilp.isEmpty() || nivel_estudio.isEmpty() || discapacidadp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor valide los datos a enviar a la Base de Datos");
        } else {
            Paciente pa = new Paciente();
            pa.setCedula(cedulap);
            pa.setApellido(apellidop);
            pa.setNombre(nombrep);
            pa.setFecha_nacimiento(fecha_nacidopa);
            pa.setTelefono(telefonop);
            pa.setDireccion(direccionp);
            pa.setAlergias(alergiap);
            pa.setOcupacion(ocupacionp);
            pa.setEdad(edadp);
            pa.setTipo_sangre(tiposangrep);
            pa.setGenero(generop);
            pa.setEstado_civil(estado_civilp);
            pa.setNivel_estudio(nivel_estudio);
            pa.setDiscapacidad(discapacidadp);

            if (ingresopa.InsertarPaciente(pa)) {
                JOptionPane.showMessageDialog(null, "Registro guardado con exito...");
                // vertablaDoctores();
            }
        }
    }

    public void verRegistrosPaciente() {
        DefaultTableModel modelopa = (DefaultTableModel) TablaPaciente.getModel();
        modelopa.setRowCount(0);
        List<Paciente> listaPacientes = ingresopa.listarDatos();
        for (Paciente paci : listaPacientes) {
            Vector paciente = new Vector();

            paciente.add(paci.getCedula());
            paciente.add(paci.getApellido());
            paciente.add(paci.getNombre());
            paciente.add(paci.getFecha_nacimiento());
            paciente.add(paci.getTelefono());
            paciente.add(paci.getDireccion());
            paciente.add(paci.getAlergias());
            paciente.add(paci.getOcupacion());
            paciente.add(paci.getEdad());
            paciente.add(paci.getTipo_sangre());
            paciente.add(paci.getGenero());
            paciente.add(paci.getEstado_civil());
            paciente.add(paci.getNivel_estudio());
            paciente.add(paci.getDiscapacidad());

            modelopa.addRow(paciente);
            TablaPaciente.setModel(modelopa);
        }

    }
    private void BtnGuardarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarDocActionPerformed

        if (!(TxtCedulaPac.getText().equals("") || TxtApellidoPac.getText().equals("") || TxtNombrePac.getText().equals("") || TxtTelefonoPac.getText().equals("") || TxtDireccionPac.getText().equals("") || ComboTipoAlergiasPac.getSelectedItem().equals("Seleccione") || TxtOcupacionPac.getText().equals("") || ComboTipoSangrePac.getSelectedItem().equals("Seleccione") || GrupoGeneroPac.isSelected(null) || ComboEstadocivilPac.getSelectedItem().equals("Seleccione") || ComboTipoEstudiPac.getSelectedItem().equals("Seleccione") || GrupoDiscapacidadPac.isSelected(null))) {
            if (validar_datosPac() == true) {
                genero_paciente();
                mostrar_edadPac();
                discapacidad_paciente();
                registrarPaciente();
                verRegistrosPaciente();
                limpiar_datosPaciente();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor asegúrese de que los campos estén con los datos correctos.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegúrese que este llenado todos los campos solicitados del paciente.");

        }
    }//GEN-LAST:event_BtnGuardarDocActionPerformed

    public boolean validar_datosPac() {
        boolean validopac = false;
        if (TxtCedulaPac.getText().matches("^\\d{10}$") && TxtApellidoPac.getText().matches("^[A-Z].{3,25}$") && TxtNombrePac.getText().matches("^[A-Z].{3,25}$") && TxtTelefonoPac.getText().matches("^\\d{8}$") && TxtDireccionPac.getText().matches("^[A-Za-z].{4,25}$") && TxtOcupacionPac.getText().matches("^[A-Za-z].{5,25}$")) {
            validopac = true;
        } else {
            validopac = false;
        }
        return validopac;
    }
    private void BtnSalirCrudDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirCrudDocActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas salir del crud de paciente.", "Confirma", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            Menu_Recepcionista mrep = new Menu_Recepcionista();
            mrep.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Sesión cancelada.");
        }
    }//GEN-LAST:event_BtnSalirCrudDocActionPerformed

    private void BtnListaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaPacienteActionPerformed
        // TODO add your handling code here:
        verRegistrosPaciente();
    }//GEN-LAST:event_BtnListaPacienteActionPerformed

    private void ComboTipoAlergiasPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoAlergiasPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoAlergiasPacActionPerformed

    private void BtnEliminarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarPacActionPerformed
        // TODO add your handling code here:
        int i = TablaPaciente.getSelectedRow();
        if (i >= 0) {

            int t = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este registro?", "Verificación de eliminar.", JOptionPane.YES_NO_OPTION);
            if (t == JOptionPane.YES_OPTION) {
                EliminarPaciente();
                limpiar_datosPaciente();
                JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
            }
            if (t == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Eliminacion cancelada.");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el registro para eliminar.");
        }
    }//GEN-LAST:event_BtnEliminarPacActionPerformed

    private void TablaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPacienteMouseClicked
        int i = TablaPaciente.getSelectedRow();

        if (i >= 0) {
            String cedulap = TablaPaciente.getValueAt(i, 0).toString();
            String apellidop = TablaPaciente.getValueAt(i, 1).toString();
            String nombrep = TablaPaciente.getValueAt(i, 2).toString();
            String fnacimientop = TablaPaciente.getValueAt(i, 3).toString();
            String telefonop = TablaPaciente.getValueAt(i, 4).toString();
            String direccionp = TablaPaciente.getValueAt(i, 5).toString();
            String alergiap = TablaPaciente.getValueAt(i, 6).toString();
            String ocupacionp = TablaPaciente.getValueAt(i, 7).toString();
            String edadp = TablaPaciente.getValueAt(i, 8).toString();
            String tiposangrep = TablaPaciente.getValueAt(i, 9).toString();
            String generop = TablaPaciente.getValueAt(i, 10).toString();
            String estado_civilp = TablaPaciente.getValueAt(i, 11).toString();
            String nivel_estudio = TablaPaciente.getValueAt(i, 12).toString();
            String discapacidadp = TablaPaciente.getValueAt(i, 13).toString();

            TxtCedulaPac.setText(cedulap);
            TxtApellidoPac.setText(apellidop);
            TxtNombrePac.setText(nombrep);
            TxtTelefonoPac.setText(telefonop);
            TxtDireccionPac.setText(direccionp);
            ComboTipoAlergiasPac.setSelectedItem(alergiap);
            TxtOcupacionPac.setText(ocupacionp);
            ComboTipoSangrePac.setSelectedItem(tiposangrep);
            if (generop.equals("Masculino")) {
                RadioBtnMasculino.setSelected(true);
            }
            if (generop.equals("Femenino")) {
                RadioBtnFemenino.setSelected(true);
            }
            if (generop.equals("No definido")) {
                RadioBtnNoDefinido.setSelected(true);
            }
            ComboEstadocivilPac.setSelectedItem(estado_civilp);
            ComboTipoEstudiPac.setSelectedItem(nivel_estudio);
            if (discapacidadp.equals("SI")) {
                RadioDiscapaSI.setSelected(true);
            }
            if (discapacidadp.equals("NO")) {
                RadioDiscapaNO.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "");
        }
    }//GEN-LAST:event_TablaPacienteMouseClicked

    private void BtnModificarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarPacActionPerformed

        int i = TablaPaciente.getSelectedRow();
        if (i >= 0) {
            if (validar_datosPac() == true) {
                mostrar_edadPac();
                genero_paciente();
                discapacidad_paciente();
                ModificarPaciente();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor asegúrese de que los campos estén con los datos correctos.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el registro para modificar.");
        }
    }//GEN-LAST:event_BtnModificarPacActionPerformed

    private void BtnBuscarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPacActionPerformed

        if (!(TxtBuscarPac.getText().equals(""))) {
            BuscarPaciente();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe ingresar la cedula en el campo, para realizar la consulta.", "Precaución  ", JOptionPane.WARNING_MESSAGE);
        }
        TxtBuscarPac.setText("");
    }//GEN-LAST:event_BtnBuscarPacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar_datosPaciente();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void BuscarPaciente() {
        DefaultTableModel modelopa = (DefaultTableModel) TablaPaciente.getModel();
        modelopa.setRowCount(0);
        List<Paciente> listaPacientes = ingresopa.consultaPaciente(TxtBuscarPac.getText());
        for (Paciente paci : listaPacientes) {
            Vector paciente = new Vector();

            paciente.add(paci.getCedula());
            paciente.add(paci.getApellido());
            paciente.add(paci.getNombre());
            paciente.add(paci.getFecha_nacimiento());
            paciente.add(paci.getTelefono());
            paciente.add(paci.getDireccion());
            paciente.add(paci.getAlergias());
            paciente.add(paci.getOcupacion());
            paciente.add(paci.getEdad());
            paciente.add(paci.getTipo_sangre());
            paciente.add(paci.getGenero());
            paciente.add(paci.getEstado_civil());
            paciente.add(paci.getNivel_estudio());
            paciente.add(paci.getDiscapacidad());

            modelopa.addRow(paciente);
            TablaPaciente.setModel(modelopa);
        }
    }

    public void ModificarPaciente() {//aquiiiiiiiiiiiiiiiiiiiiiiiiii
        String cedulap = TxtCedulaPac.getText();
        String apellidop = TxtApellidoPac.getText();
        String nombrep = TxtNombrePac.getText();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        String fnacimientop = formatoFecha.format(DateFnaciPaci.getDate());
        String telefonop = TxtTelefonoPac.getText();
        String direccionp = TxtDireccionPac.getText();
        String alergiap = ComboTipoAlergiasPac.getSelectedItem().toString();
        String ocupacionp = TxtOcupacionPac.getText();
        int edadp = Integer.parseInt(edadpac);
        String tiposangrep = ComboTipoSangrePac.getSelectedItem().toString();
        String generop = generopac;
        String estado_civilp = ComboEstadocivilPac.getSelectedItem().toString();
        String nivel_estudio = ComboTipoEstudiPac.getSelectedItem().toString();
        String discapacidadp = discapacidadPac;

        //validamos los campos a enviar a la base de datos
        if (cedulap.isEmpty() || apellidop.isEmpty() || nombrep.isEmpty() || fnacimientop.isEmpty() || telefonop.isEmpty() || direccionp.isEmpty() || alergiap.isEmpty() || ocupacionp.isEmpty() || edadp <= 0 || tiposangrep.isEmpty() || generop.isEmpty() || estado_civilp.isEmpty() || nivel_estudio.isEmpty() || discapacidadp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor valide los datos a enviar a la Base de Datos");
        } else {
            Paciente pac = new Paciente();
            pac.setCedula(cedulap);
            pac.setApellido(apellidop);
            pac.setNombre(nombrep);
            pac.setFecha_nacimiento(fnacimientop);
            pac.setTelefono(telefonop);
            pac.setDireccion(direccionp);
            pac.setAlergias(alergiap);
            pac.setOcupacion(ocupacionp);
            pac.setEdad(edadp);
            pac.setTipo_sangre(tiposangrep);
            pac.setGenero(generop);
            pac.setEstado_civil(estado_civilp);
            pac.setNivel_estudio(nivel_estudio);
            pac.setDiscapacidad(discapacidadp);
            if (ingresopa.ModificarPaciente(pac)) {
                JOptionPane.showMessageDialog(null, "Modificasion con exito");
                verRegistrosPaciente();
                limpiar_datosPaciente();
            }
        }

    }

    public void EliminarPaciente() {
        String cedulap = TxtCedulaPac.getText();
        if (TxtCedulaPac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor debe seleccionar un articulo de la lista");
        } else {
            if (ingresopa.EliminarPaciente(cedulap)) {
                JOptionPane.showMessageDialog(null, "Registro eliminado con exito...");
                mostrar_pacientes();
            }
        }
    }

    public void limpiar_datosPaciente() {
        TxtCedulaPac.setText("");
        TxtApellidoPac.setText("");
        TxtNombrePac.setText("");
        //   TxtFecha_Nacimiento_Pac.setText("");
        TxtTelefonoPac.setText("");
        TxtDireccionPac.setText("");
        ComboTipoAlergiasPac.setSelectedItem("Seleccione");
        TxtOcupacionPac.setText("");
        ComboTipoSangrePac.setSelectedItem("Seleccione");
        GrupoGeneroPac.clearSelection();
        ComboEstadocivilPac.setSelectedItem("Seleccione");
        ComboTipoEstudiPac.setSelectedItem("Seleccione");
        GrupoDiscapacidadPac.clearSelection();

    }

    public void mostrar_pacientes() {
        String matrizPac[][] = new String[Lista_Pacientes.size()][14];

        for (int i = 0; i < Lista_Pacientes.size(); i++) {
            matrizPac[i][0] = Lista_Pacientes.get(i).getCedula();
            matrizPac[i][1] = Lista_Pacientes.get(i).getApellido();
            matrizPac[i][2] = Lista_Pacientes.get(i).getNombre();
            matrizPac[i][3] = Lista_Pacientes.get(i).getFecha_nacimiento();
            matrizPac[i][4] = Lista_Pacientes.get(i).getTelefono();
            matrizPac[i][5] = Lista_Pacientes.get(i).getDireccion();
            matrizPac[i][6] = Lista_Pacientes.get(i).getAlergias();
            matrizPac[i][7] = Lista_Pacientes.get(i).getOcupacion();
            matrizPac[i][8] = String.valueOf(Lista_Pacientes.get(i).getEdad());
            matrizPac[i][9] = Lista_Pacientes.get(i).getTipo_sangre();
            matrizPac[i][10] = Lista_Pacientes.get(i).getGenero();
            matrizPac[i][11] = Lista_Pacientes.get(i).getEstado_civil();
            matrizPac[i][12] = Lista_Pacientes.get(i).getNivel_estudio();
            matrizPac[i][13] = Lista_Pacientes.get(i).getDiscapacidad();

        }
        TablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
                matrizPac,
                new String[]{
                    "Cedula", "Apellido", "Nombre", "Fecha de nacimiento", "Telefono", "Direccion", "Alergia", "Ocupación", "Edad", "Tipo sangre", "Genero", "Estado civil", "Nivel Estudio", "Discapacidad"
                }
        ));

    }

    public void genero_paciente() {
        GrupoGeneroPac.add(RadioBtnMasculino);
        GrupoGeneroPac.add(RadioBtnFemenino);
        GrupoGeneroPac.add(RadioBtnNoDefinido);
        if (RadioBtnMasculino.isSelected()) {
            generopac = "Masculino";
        }
        if (RadioBtnFemenino.isSelected()) {
            generopac = "Femenino";
        }
        if (RadioBtnNoDefinido.isSelected()) {
            generopac = "No definido";
        }
    }

    public void discapacidad_paciente() {
        GrupoDiscapacidadPac.add(RadioDiscapaSI);
        GrupoDiscapacidadPac.add(RadioDiscapaNO);
        if (RadioDiscapaSI.isSelected()) {
            discapacidadPac = "SI";
        }
        if (RadioDiscapaNO.isSelected()) {
            discapacidadPac = "NO";
        }
    }

    public void mostrar_edadPac() {
        edadpac = SpinerEdadPac.getValue().toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarPac;
    private javax.swing.JButton BtnEliminarPac;
    private javax.swing.JButton BtnGuardarDoc;
    private javax.swing.JButton BtnListaPaciente;
    private javax.swing.JButton BtnModificarPac;
    private javax.swing.JButton BtnSalirCrudDoc;
    private javax.swing.JComboBox<String> ComboEstadocivilPac;
    private javax.swing.JComboBox<String> ComboTipoAlergiasPac;
    private javax.swing.JComboBox<String> ComboTipoEstudiPac;
    private javax.swing.JComboBox<String> ComboTipoSangrePac;
    private com.toedter.calendar.JDateChooser DateFnaciPaci;
    private javax.swing.ButtonGroup GrupoDiscapacidadPac;
    private javax.swing.ButtonGroup GrupoGeneroPac;
    private javax.swing.JRadioButton RadioBtnFemenino;
    private javax.swing.JRadioButton RadioBtnMasculino;
    private javax.swing.JRadioButton RadioBtnNoDefinido;
    private javax.swing.JRadioButton RadioDiscapaNO;
    private javax.swing.JRadioButton RadioDiscapaSI;
    private javax.swing.JSpinner SpinerEdadPac;
    private javax.swing.JTable TablaPaciente;
    private javax.swing.JTextField TxtApellidoPac;
    private javax.swing.JTextField TxtBuscarPac;
    private javax.swing.JTextField TxtCedulaPac;
    private javax.swing.JTextField TxtDireccionPac;
    private javax.swing.JTextField TxtNombrePac;
    private javax.swing.JTextField TxtOcupacionPac;
    private javax.swing.JTextField TxtTelefonoPac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
