/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package M_Recepcionista;

import Comportamientos.IgresarMedicamentos;
import clases.Medicamentos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Descarga_Medicamentos extends javax.swing.JFrame {

    /**
     * Creates new form Descarga_Medicamentos
     */
    IgresarMedicamentos inmed = new IgresarMedicamentos();
    String cod_medicamento = "";

    public Descarga_Medicamentos() {
        initComponents();
        cargarTablaMedicamento();
        txtNombre.setEnabled(false);
        txtUnidadM.setEnabled(false);
        txtCantidad.setEditable(false);
        ComboTDM.setEnabled(false);
        Combo_ViaAdmin.setEnabled(false);
        ComboPresent.setEnabled(false);
        DateIngresos.setEnabled(false);
        DateCaducidad.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboPresent = new javax.swing.JComboBox<>();
        ComboTDM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Combo_ViaAdmin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUnidadM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        DateIngresos = new com.toedter.calendar.JDateChooser();
        DateCaducidad = new com.toedter.calendar.JDateChooser();
        BtnModificarMed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicamentos = new javax.swing.JTable();
        TxtCantidadDes = new javax.swing.JTextField();
        BtnRegistros = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        TxtBuscarMedicamentos = new javax.swing.JTextField();
        BtnBuscarMed = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Despacho de Medicamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bell MT", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Presentacion:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Unidad de Medida:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de Medicamentos :");

        ComboPresent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Tabletas", "Grageas", "Comprimidos", "Capsulas", "Jarabe", "Elipser", "Suspesiones", "Polvo", "Otros" }));
        ComboPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPresentActionPerformed(evt);
            }
        });

        ComboTDM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Solido", "Semi Solido", "Liquido", "Gases", "Otros" }));
        ComboTDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTDMActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Via de Administracion:");

        Combo_ViaAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Oftálmica", "Ótica", "Nasal", "Oral", "Tópica", "Parenteral", "Rectal", "Vaginal" }));
        Combo_ViaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_ViaAdminActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de Caducidad:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtUnidadM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadMKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Fecha de Ingreso:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUnidadM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboTDM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(Combo_ViaAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(DateIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboTDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUnidadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Combo_ViaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(DateIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(DateCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnModificarMed.setText("Despachar");
        BtnModificarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarMedActionPerformed(evt);
            }
        });

        TablaMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Tipo Medicamento", "Medicamentos", "Presentacion", "Unidad Medidad", "Via Administracion", "Fecha Ingreso", "Fecha Caducidad", "Cantidad"
            }
        ));
        TablaMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMedicamentos);

        TxtCantidadDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadDesActionPerformed(evt);
            }
        });
        TxtCantidadDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCantidadDesKeyTyped(evt);
            }
        });

        BtnRegistros.setText("Ver Registros");
        BtnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Nombre Medicamento:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad Actual:");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Cantidad a despachar:");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel4.setText("DESPACHO DE MEDICAMENTOS");

        jButton5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(332, 332, 332)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TxtBuscarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarMedicamentosActionPerformed(evt);
            }
        });
        TxtBuscarMedicamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarMedicamentosKeyTyped(evt);
            }
        });

        BtnBuscarMed.setText("Buscar");
        BtnBuscarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMedActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese el nombre del medicamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCantidadDes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnRegistros)
                                            .addComponent(BtnLimpiar))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnModificarMed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(TxtBuscarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscarMed)
                                .addGap(154, 154, 154)))))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtCantidadDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnModificarMed))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(BtnLimpiar))
                                    .addComponent(TxtBuscarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BtnBuscarMed))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnRegistros))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, debe ingresar nombre.");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Error usted no puede editar esta <<CANTIDAD>>");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void ComboPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPresentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPresentActionPerformed

    private void ComboTDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTDMActionPerformed

    private void Combo_ViaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_ViaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_ViaAdminActionPerformed

    private void txtUnidadMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadMKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, la unidad de medida.");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_txtUnidadMKeyTyped

    private void cargarTablaMedicamento() {
        DefaultTableModel tblModelo = (DefaultTableModel) TablaMedicamentos.getModel();

        tblModelo.setNumRows(0);
        List<Medicamentos> listamedicamento = inmed.ListMedicamentos();

        listamedicamento.stream().forEach(p -> {

            p.getCantidad();
            String can = String.valueOf(p.getCantidad());
            String[] medica = {p.getCodigoM(), p.getNombreM(), p.getTiposM(), p.getMedicamentos(), p.getPresentacionM(), p.getUnidadesMM(), p.getVia_AdministracionM(), p.getFecha_IngresoM(), p.getFecha_caducidad(), can};
            tblModelo.addRow(medica);
        });
    }
    private void TablaMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicamentosMouseClicked
        // TODO add your handling code here:
        int i = TablaMedicamentos.getSelectedRow();
        if (i <= 5000) {

            cod_medicamento = TablaMedicamentos.getValueAt(i, 0).toString();
            String nom_medicamento = TablaMedicamentos.getValueAt(i, 1).toString();
            String tipo_medicamento = TablaMedicamentos.getValueAt(i, 2).toString();
            String medicamento = TablaMedicamentos.getValueAt(i, 3).toString();
            String presentacion = TablaMedicamentos.getValueAt(i, 4).toString();
            String unidad_medida = TablaMedicamentos.getValueAt(i, 5).toString();
            String via_administracion = TablaMedicamentos.getValueAt(i, 6).toString();
            String fecha_ingreso = TablaMedicamentos.getValueAt(i, 7).toString();

            String fecha_caducidad = TablaMedicamentos.getValueAt(i, 8).toString();
            String cantidad_medicamentos = TablaMedicamentos.getValueAt(i, 9).toString();

            String fechain = (String) TablaMedicamentos.getValueAt(i, 7);
            Date fechaingre;
            try {
                fechaingre = new SimpleDateFormat("dd/MM/yyyy").parse(fechain);
                DateIngresos.setDate(fechaingre);
            } catch (ParseException ex) {
                Logger.getLogger(Descarga_Medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            }
            String fecha2 = (String) TablaMedicamentos.getValueAt(i, 8);
            Date fechas2 = null;
            try {
                fechas2 = new SimpleDateFormat("dd/MM/yyyy").parse(fecha2);
                DateCaducidad.setDate(fechas2);
            } catch (ParseException ex) {
                Logger.getLogger(Descarga_Medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtNombre.setText(nom_medicamento);
            ComboTDM.setSelectedItem(tipo_medicamento);
            ComboPresent.setSelectedItem(presentacion);
            txtUnidadM.setText(unidad_medida);
            Combo_ViaAdmin.setSelectedItem(via_administracion);
            txtCantidad.setText(cantidad_medicamentos);

        } else {
            if (i >= 0) {
                cod_medicamento = TablaMedicamentos.getValueAt(i, 0).toString();
                String nom_medicamento = TablaMedicamentos.getValueAt(i, 1).toString();
                String tipo_medicamento = TablaMedicamentos.getValueAt(i, 2).toString();
                String medicamento = TablaMedicamentos.getValueAt(i, 3).toString();
                String presentacion = TablaMedicamentos.getValueAt(i, 4).toString();
                String unidad_medida = TablaMedicamentos.getValueAt(i, 5).toString();
                String via_administracion = TablaMedicamentos.getValueAt(i, 6).toString();
                String fecha_ingreso = TablaMedicamentos.getValueAt(i, 7).toString();

                String fecha_caducidad = TablaMedicamentos.getValueAt(i, 8).toString();
                String cantidad_medicamentos = TablaMedicamentos.getValueAt(i, 9).toString();

                String fechain = (String) TablaMedicamentos.getValueAt(i, 7);
                Date fechaingre;
                try {
                    fechaingre = new SimpleDateFormat("dd/MM/yyyy").parse(fechain);
                    DateIngresos.setDate(fechaingre);
                } catch (ParseException ex) {
                    Logger.getLogger(Descarga_Medicamentos.class.getName()).log(Level.SEVERE, null, ex);
                }
                String fecha2 = (String) TablaMedicamentos.getValueAt(i, 8);
                Date fechas2 = null;
                try {
                    fechas2 = new SimpleDateFormat("dd/MM/yyyy").parse(fecha2);
                    DateCaducidad.setDate(fechas2);
                } catch (ParseException ex) {
                    Logger.getLogger(Descarga_Medicamentos.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNombre.setText(nom_medicamento);
                ComboTDM.setSelectedItem(tipo_medicamento);
                ComboPresent.setSelectedItem(presentacion);
                txtUnidadM.setText(unidad_medida);
                Combo_ViaAdmin.setSelectedItem(via_administracion);
                txtCantidad.setText(cantidad_medicamentos);

            } else {
                JOptionPane.showMessageDialog(null, "6");
            }
        }
    }//GEN-LAST:event_TablaMedicamentosMouseClicked

    public void modificarDatosMedica() {

        int canAC = Integer.parseInt(txtCantidad.getText());
        int canDes = Integer.parseInt(TxtCantidadDes.getText());
        int totalActual = canAC - canDes;

        String idmed = cod_medicamento;

        int j = TablaMedicamentos.getSelectedRow();

        if (j >= 0) {
            if (cod_medicamento.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor debe seleccionar un articulo de la lista");
            } else {
                IgresarMedicamentos modifi = new IgresarMedicamentos();
                modifi.setNombreM(txtNombre.getText());
                modifi.setTiposM(ComboTDM.getSelectedItem().toString());
                modifi.setMedicamentos("Generico");
                modifi.setPresentacionM(ComboPresent.getSelectedItem().toString());
                modifi.setUnidadesMM(txtUnidadM.getText());
                modifi.setVia_AdministracionM(Combo_ViaAdmin.getSelectedItem().toString());
                modifi.setFecha_IngresoM(((JTextField) DateIngresos.getDateEditor().getUiComponent()).getText());
                modifi.setFecha_caducidad(((JTextField) DateCaducidad.getDateEditor().getUiComponent()).getText());
                modifi.setCantidad(totalActual);
                if (modifi.ModificarMedicamento(idmed)) {
                    System.out.println("Conexion exitosa");
                } else {
                    System.out.println("Error en conexion");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe seleccionar un articulo de la lista");

        }
    }

    public void limpiar_datos() {
        txtNombre.setText("");
        ComboTDM.setSelectedItem("Seleccione");
        ComboPresent.setSelectedItem("Seleccione");
        txtUnidadM.setText("");
        Combo_ViaAdmin.setSelectedItem("Seleccione");
        txtCantidad.setText("");
        ((JTextField) DateIngresos.getDateEditor().getUiComponent()).setText(null);
        ((JTextField) DateCaducidad.getDateEditor().getUiComponent()).setText(null);
    }


    private void BtnModificarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarMedActionPerformed
        // TODO add your handling code here
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error ud no ha seleccionado ningun medicamento para despachar.");
        } else {
            if (TxtCantidadDes.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Error, el campo de despacho esta vacio");

            } else {
                if (!(TxtCantidadDes.getText().matches("[0-9]{1,2}"))) {
                    JOptionPane.showMessageDialog(null, "La cantidad a sacar exede la restriccion de medicamentos.");

                } else {

                    int canAC = Integer.parseInt(txtCantidad.getText());
                    int canDes = Integer.parseInt(TxtCantidadDes.getText());
                    if (canDes >= 10) {
                        JOptionPane.showMessageDialog(null, "Error ud no puede sacar mas de 10 unidades.");
                    } else {
                        if (canDes > canAC) {
                            JOptionPane.showMessageDialog(null, "Error ud no puede despachar, ya que la cantidad actual es mayor al despacho.");
                        } else {
                            modificarDatosMedica();
                            cargarTablaMedicamento();
                            limpiar_datos();
                        }

                    }
                }
            }
        }
        TxtCantidadDes.setText("");
    }//GEN-LAST:event_BtnModificarMedActionPerformed

    private void TxtCantidadDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadDesActionPerformed

    private void BtnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrosActionPerformed
        // TODO add your handling code here
        cargarTablaMedicamento();
    }//GEN-LAST:event_BtnRegistrosActionPerformed

    private void TxtCantidadDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantidadDesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad");
        }
    }//GEN-LAST:event_TxtCantidadDesKeyTyped

    private void TxtBuscarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarMedicamentosActionPerformed

    private void TxtBuscarMedicamentosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarMedicamentosKeyTyped
        // TODO add your handling code here:
        char vn = evt.getKeyChar();
        if (Character.isDigit(vn)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, debe ingresar nombre.");
        }

        if (Character.isLowerCase(vn)) {

            evt.setKeyChar(Character.toUpperCase(vn));
        }
    }//GEN-LAST:event_TxtBuscarMedicamentosKeyTyped

    private void BtnBuscarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMedActionPerformed
        // TODO add your handling code here:
        if (TxtBuscarMedicamentos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error el campo de busqueda esta vacio.");

        } else {
            Busqueda_Medicamento();
        }
        TxtBuscarMedicamentos.setText("");
    }//GEN-LAST:event_BtnBuscarMedActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar_datos();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    public void Busqueda_Medicamento() {
        DefaultTableModel tblModelo = (DefaultTableModel) TablaMedicamentos.getModel();

        tblModelo.setNumRows(0);
        List<Medicamentos> listaMedicamentos = inmed.consulta_Medicamento(TxtBuscarMedicamentos.getText());

        listaMedicamentos.stream().forEach(p -> {
            p.getCantidad();
            String cant = String.valueOf(p.getCantidad());
            String[] medic = {p.getCodigoM(), p.getNombreM(), p.getTiposM(), p.getMedicamentos(), p.getPresentacionM(), p.getUnidadesMM(), p.getVia_AdministracionM(), p.getFecha_IngresoM(), p.getFecha_caducidad(), cant};
            tblModelo.addRow(medic);
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Descarga_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Descarga_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Descarga_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Descarga_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Descarga_Medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarMed;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificarMed;
    private javax.swing.JButton BtnRegistros;
    private javax.swing.JComboBox<String> ComboPresent;
    private javax.swing.JComboBox<String> ComboTDM;
    private javax.swing.JComboBox<String> Combo_ViaAdmin;
    private com.toedter.calendar.JDateChooser DateCaducidad;
    private com.toedter.calendar.JDateChooser DateIngresos;
    private javax.swing.JTable TablaMedicamentos;
    private javax.swing.JTextField TxtBuscarMedicamentos;
    private javax.swing.JTextField TxtCantidadDes;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUnidadM;
    // End of variables declaration//GEN-END:variables
}
